const WORKER="https://bioglow.robootikaring.workers.dev";
const $=id=>document.getElementById(id);
const go=id=>$(id)?.scrollIntoView({behavior:"smooth"});
const esc=s=>String(s??"").replace(/[&<>\"]/g,c=>({"&":"&amp;","<":"&lt;",">":"&gt;",'\"':"&quot;"}[c]));
const norm=s=>String(s||"").trim().toLowerCase().replace(/\s+/g," ");
let chosenPlant=null,chosenFile=null,timer=null,marker=null;
const map=L.map("map").setView([58.65,25.1],7);L.tileLayer("https://{s}.tile.openstreetmap.org/{z}/{x}/{y}.png",{attribution:"© OpenStreetMap"}).addTo(map);
function matchesName(name,list){const n=norm(name);return list.some(x=>n===norm(x)||n.startsWith(norm(x)+" ")||norm(x).startsWith(n+" "))}
function isInvasive(name){return matchesName(name,INVASIVE)}
function protectedInfo(name){if(matchesName(name,PROTECTED_I))return{category:"I",common:null};if(matchesName(name,PROTECTED_II))return{category:"II",common:null};const n=norm(name);for(const [common,names] of PROTECTED_III){if(names.some(x=>n===norm(x)||n.startsWith(norm(x)+" ")||norm(x).startsWith(n+" ")))return{category:"III",common}}return null}
function protectionBadge(name){const p=protectedInfo(name);if(!p)return '<span class="badge bb">Kaitsekategooria: puudub</span>';return `<span class="badge protect">🛡️ ${p.category} kaitsekategooria</span>`}
function protectionNote(name){const p=protectedInfo(name);if(!p)return"";if(p.category==="I"||p.category==="II")return `<div class="protectNote"><b>🛡️ Kaitsealune liik (${p.category} kategooria).</b> BioGlow ei kuva ega kasuta siin tundlikke täpseid kasvukohti. Loodusest isendite võtmise või ümberistutamise asemel toeta liigi kasvukohta ja kasuta ainult seaduslikust allikast pärit taime.</div>`;return `<div class="protectNote"><b>🛡️ III kaitsekategooria liik.</b> Ära võta taime loodusest. Kui eesmärk on looduskaitse, eelista olemasoleva kasvukoha hoidmist või taastamist.</div>`}
$("plantInput").oninput=()=>{clearTimeout(timer);chosenPlant=null;$("chosen").classList.add("hidden");const q=$("plantInput").value.trim();if(q.length<2){$("suggest").classList.add("hidden");return}timer=setTimeout(()=>loadSuggestions(q),220)};
async function gbifSuggest(q){const r=await fetch(`https://api.gbif.org/v1/species/suggest?q=${encodeURIComponent(q)}&limit=10`);if(!r.ok)throw Error(`GBIF species HTTP ${r.status}`);const d=await r.json();return d.filter(x=>x.rank==="SPECIES"||x.rank==="SUBSPECIES")}
async function gbifMatch(name){const r=await fetch(`https://api.gbif.org/v1/species/match?name=${encodeURIComponent(name)}&kingdom=Plantae`);if(!r.ok)throw Error(`GBIF match HTTP ${r.status}`);const x=await r.json();if(!x.usageKey&&!x.speciesKey)return null;return{key:x.usageKey||x.speciesKey,canonicalName:x.canonicalName||x.scientificName||name,scientificName:x.scientificName||x.canonicalName||name,rank:x.rank||"SPECIES"}}
function suggestionButton(x,raw=""){const sci=x.canonicalName||x.scientificName||raw||"",friendly=DISPLAY[sci]||x.vernacularName||raw||"";return `<button type="button" onclick="choosePlant(${x.key||x.usageKey},'${encodeURIComponent(sci)}','${encodeURIComponent(friendly)}')"><b>${esc(friendly||sci)}</b>${friendly&&friendly!==sci?`<br><small>${esc(sci)}</small>`:""}</button>`}
async function loadSuggestions(q){try{const alias=SIMPLE_NAMES[norm(q)];let items=[];if(alias){const exact=await gbifMatch(alias).catch(()=>null);if(exact)items.push(exact)}const suggested=await gbifSuggest(alias||q).catch(()=>[]),seen=new Set(items.map(x=>x.key||x.usageKey));for(const x of suggested){const k=x.key||x.usageKey;if(!seen.has(k)){items.push(x);seen.add(k)}}$("suggest").innerHTML=items.slice(0,8).map(x=>suggestionButton(x,q)).join("")||'<button type="button">Ei leidnud vastet.</button>';$("suggest").classList.remove("hidden")}catch(e){console.error(e);$("suggest").innerHTML='<button type="button">Taimede otsing ebaõnnestus. Proovi uuesti.</button>';$("suggest").classList.remove("hidden")}}
function choosePlant(key,sciEnc,commonEnc){const scientific=decodeURIComponent(sciEnc),common=decodeURIComponent(commonEnc||"");chosenPlant={key:Number(key),scientific,common:common||DISPLAY[scientific]||scientific};$("plantInput").value=chosenPlant.common;$("chosen").innerHTML=`Valitud: <b>${esc(chosenPlant.common)}</b><br><small>${esc(scientific)}</small><br>${protectionBadge(scientific)}`;$("chosen").classList.remove("hidden");$("suggest").classList.add("hidden")}
async function resolveTypedPlant(){if(chosenPlant)return chosenPlant;const raw=$("plantInput").value.trim();if(!raw)return null;const alias=SIMPLE_NAMES[norm(raw)];try{let x=alias?await gbifMatch(alias):null;if(!x){const a=await gbifSuggest(alias||raw);x=a[0]||null}if(!x)return null;const sci=x.canonicalName||x.scientificName||alias||raw;choosePlant(x.key||x.usageKey,encodeURIComponent(sci),encodeURIComponent(DISPLAY[sci]||x.vernacularName||raw));return chosenPlant}catch(e){console.error(e);return null}}
$("files").onchange=()=>setFile($("files").files[0]);$("drop").ondragover=e=>{e.preventDefault();$("drop").classList.add("drag")};$("drop").ondragleave=()=>$("drop").classList.remove("drag");$("drop").ondrop=e=>{e.preventDefault();$("drop").classList.remove("drag");setFile(e.dataTransfer.files[0])};
function setFile(f){if(!f||!/\.jpe?g$/i.test(f.name)){chosenFile=null;$("status").textContent="Kasuta JPG/JPEG fotot.";return}chosenFile=f;$("preview").src=URL.createObjectURL(f);$("preview").style.display="block";$("status").textContent=`Foto valmis: ${f.name}`}
async function nearby(lat,lon){const u=new URL("https://api.gbif.org/v1/occurrence/search");u.searchParams.set("decimalLatitude",`${lat-.09},${lat+.09}`);u.searchParams.set("decimalLongitude",`${lon-.16},${lon+.16}`);u.searchParams.set("kingdomKey","6");u.searchParams.set("country","EE");u.searchParams.set("hasCoordinate","true");u.searchParams.set("limit","300");const r=await fetch(u);if(!r.ok)throw Error("GBIF HTTP "+r.status);const d=await r.json(),m=new Map();for(const x of d.results||[]){if(!x.speciesKey||!x.species)continue;let v=m.get(x.speciesKey)||{key:x.speciesKey,name:DISPLAY[x.species]||x.vernacularName||x.species,scientific:x.species,count:0,latest:"",media:"",license:"",creator:""};v.count++;if((x.eventDate||"")>v.latest)v.latest=x.eventDate||"";const med=(x.media||[]).find(z=>z.identifier);if(!v.media&&med){v.media=med.identifier;v.license=med.license||"";v.creator=med.creator||""}m.set(x.speciesKey,v)}return[...m.values()].sort((a,b)=>b.count-a.count)}
async function mediaFor(x){if(x.media)return x;try{const r=await fetch(`https://api.gbif.org/v1/occurrence/search?taxon_key=${x.key}&media_type=StillImage&limit=8`),d=await r.json();for(const o of d.results||[]){const m=(o.media||[]).find(z=>z.identifier);if(m){x.media=m.identifier;x.license=m.license||"";x.creator=m.creator||"";break}}}catch(e){console.warn("media",e)}return x}
async function selectedCount(key,lat,lon){const u=new URL("https://api.gbif.org/v1/occurrence/search");u.searchParams.set("taxon_key",key);u.searchParams.set("decimalLatitude",`${lat-.09},${lat+.09}`);u.searchParams.set("decimalLongitude",`${lon-.16},${lon+.16}`);u.searchParams.set("country","EE");u.searchParams.set("hasCoordinate","true");u.searchParams.set("limit","0");const r=await fetch(u);if(!r.ok)throw Error(`GBIF count HTTP ${r.status}`);const d=await r.json();return d.count||0}
async function photoAI(f,gps){try{const fd=new FormData();fd.append("image",f);fd.append("latitude",gps[0]);fd.append("longitude",gps[1]);const r=await fetch(WORKER+"/identify",{method:"POST",body:fd});if(!r.ok)throw Error(`AI HTTP ${r.status}`);const d=await r.json(),b=d.results?.[0];return b?.species?.commonNames?.[0]||b?.species?.scientificNameWithoutAuthor||"Analüüs tehtud"}catch(e){console.warn(e);return"AI polnud saadaval"}}
function fact(i,t){const b=$("facts")?.children[i]?.querySelector("b");if(b)b.textContent=t}function cardImage(x){return x.media?`<img src="${esc(x.media)}" alt="${esc(x.name)}" loading="lazy" referrerpolicy="no-referrer">`:'<div style="height:180px;display:grid;place-items:center;background:#edf2ed;font-size:42px">🌿</div>'}function credit(x){return`<div class="meta">Pilt: GBIF${x.creator?` · ${esc(x.creator)}`:""}${x.license?` · ${esc(x.license)}`:""}</div>`}
async function renderConservation(list){const hits=list.map(x=>({x,info:protectedInfo(x.scientific)})).filter(z=>z.info?.category==="III");if(!hits.length){$("conservation").innerHTML='<div class="conserve"><b>🛡️ Looduskaitse soovitus</b><div class="conservationIntro">Selle avaliku lähiala päringu põhjal ei leitud III kaitsekategooria taime. BioGlow ei kuva I–II kategooria tundlikke täpseid kasvukohti. Eelista kohalikku liiki ja säilita olemasolevat looduslikku taimestikku.</div></div>';return}hits.sort((a,b)=>a.x.count-b.x.count);const h=hits[0];await mediaFor(h.x);const img=h.x.media?`<img src="${esc(h.x.media)}" alt="${esc(h.info.common||h.x.name)}" referrerpolicy="no-referrer">`:'<div style="height:150px;border-radius:15px;background:#dcebf1;display:grid;place-items:center;font-size:40px">🛡️</div>';$("conservation").innerHTML=`<div class="conserve"><div class="conserveGrid">${img}<div><b style="font-size:20px">🛡️ Looduskaitseline võimalus: ${esc(h.info.common||h.x.name)}</b><div class="latin">${esc(h.x.scientific)} · III kaitsekategooria</div><p>Selle liigi kohta oli avalikus lähiala päringus <b>${h.x.count}</b> vaatlust. See on BioGlow prototüübi looduskaitse-signaal: pigem toeta või taasta talle sobivat kasvukohta, mitte ära võta taime loodusest ümberistutamiseks.</p><div class="meta">Valik põhineb III kaitsekategoorial ja väiksemal avalike lähivaatluste arvul; see ei ole ametlik looduskaitse prioriteetsuse hinnang.</div>${h.x.media?credit(h.x):""}</div></div></div>`}
async function renderAlternatives(list){const good=list.filter(x=>!isInvasive(x.scientific)&&!protectedInfo(x.scientific)&&x.key!==chosenPlant.key).slice(0,6);await Promise.all(good.map(mediaFor));$("plants").innerHTML=good.length?good.map((x,i)=>`<article class="plant">${cardImage(x)}<div class="pb"><span class="badge ${i<2?"bg":i<4?"by":"bb"}">${i<2?"Tugev kandidaat":i<4?"Hea kandidaat":"Võimalik"}</span><h3>${esc(x.name)}</h3><div class="latin">${esc(x.scientific)}</div><div class="reason">Avalikus lähiala päringus ${x.count} vaatlust. Kaitsealused ja invasiivsed liigid on sellest istutussoovituste nimekirjast välja jäetud.</div>${x.media?credit(x):""}</div></article>`).join(""):'<div class="notice">Tavalisi (mitte kaitsealuseid ega invasiivseid) alternatiive ei leitud piisavalt.</div>'}
function renderSuitability(n,best){const p=protectedInfo(chosenPlant.scientific),ratio=best>0?n/best:0,protect=protectionNote(chosenPlant.scientific);if(isInvasive(chosenPlant.scientific)){$("verdict").className="verdict no";$("verdict").innerHTML=`<h2>❌ EI SOBI</h2>${protectionBadge(chosenPlant.scientific)}<br><b>${esc(chosenPlant.common)}</b> (${esc(chosenPlant.scientific)}) on BioGlow invasiivsete/keelatud taimede kontrollnimekirjas. Ära istuta ega külva seda loodusesse.${protect}`;return}let cls="no",title="❌ EI SOBI HÄSTI",msg="Selle taime kohta ei leitud lähialalt avalikku tõendit. Vaata allpool tugevamaid alternatiive.";if(ratio>=.5){cls="ok";title="✅ SOBIB";msg=`Selle taime kohta leiti lähialalt ${n} avalikku kirjet. Kohalik levik toetab valikut.`}else if(ratio>=.18||n>0){cls="maybe";title="🟡 VÕIB SOBIDA";msg=`Selle taime kohta leiti lähialalt ${n} kirjet, kuid teistel liikidel on tugevam kohalik tõendus.`}if(p&&(p.category==="I"||p.category==="II"))msg=`${msg} Kuna tegu on ${p.category} kaitsekategooria liigiga, ei kuva BioGlow selle liigi tundlikke kohalikke kasvukohaandmeid.`;$("verdict").className=`verdict ${cls}`;$("verdict").innerHTML=`<h2>${title}</h2>${protectionBadge(chosenPlant.scientific)}<div class="selectedName"><b>${esc(chosenPlant.common)}</b><br><small>${esc(chosenPlant.scientific)}</small></div><p>${msg}</p>${protect}`}
async function runCheck(){try{if(!await resolveTypedPlant()){$("status").textContent="Ma ei leidnud seda taime. Proovi näiteks „kadakas“, „tamm“, „jugapuu“ või täpsemat nime.";return}if(!chosenFile){$("status").textContent="Lisa koha foto.";return}$("status").textContent="Analüüsin…";$("verdict").className="muted";$("verdict").textContent="⏳ Arvutan sobivust…";$("plants").innerHTML='<div class="muted">⏳ Otsin alternatiive ja pilte…</div>';$("conservation").innerHTML='<div class="conserve">⏳ Otsin avalikke III kaitsekategooria taimi…</div>';let ex={};try{ex=await exifr.parse(chosenFile,{gps:true})||{}}catch(e){console.warn("EXIF",e)}const gps=ex.latitude!=null&&ex.longitude!=null?[ex.latitude,ex.longitude]:null;if(!gps){fact(0,"Puudub");$("verdict").className="verdict no";$("verdict").innerHTML='<h2>❌ GPS puudub</h2>Kasuta originaalfotot, millel asukoht on alles.';$("status").textContent="GPS-i ei leitud.";return}if(marker)map.removeLayer(marker);marker=L.marker(gps).addTo(map).bindPopup("Analüüsitav koht").openPopup();map.setView(gps,14);setTimeout(()=>map.invalidateSize(),80);fact(0,gps.map(x=>x.toFixed(5)).join(", "));fact(1,"Analüüsin…");fact(2,"Otsin…");const[list,ai]=await Promise.all([nearby(gps[0],gps[1]),photoAI(chosenFile,gps)]);fact(1,ai);fact(2,list.length?list.reduce((s,x)=>s+x.count,0)+" vaatlust":"0 vaatlust");if(!list.length)throw Error("Selle koha kohta ei saadud piisavalt avalikke taimevaatlusi.");const n=await selectedCount(chosenPlant.key,gps[0],gps[1]).catch(()=>0),best=list[0]?.count||1;renderSuitability(n,best);await Promise.all([renderAlternatives(list),renderConservation(list)]);$("status").textContent="Valmis.";go("results")}catch(e){console.error(e);$("status").textContent=`Viga: ${e.message||e}`;$("verdict").className="verdict no";$("verdict").innerHTML=`<h2>⚠️ Analüüs ebaõnnestus</h2><div>${esc(e.message||e)}</div><div class="meta">Proovi uuesti. Kui viga kordub, on tõenäoliselt mõni välisandmeallikas ajutiselt kättesaamatu.</div>`}}
