// BioGlow V8 environment layer
(function(){
  const LAND_LABELS={wetland:"Märgala",wood:"Mets",forest:"Mets",meadow:"Niit / rohumaa",grass:"Rohumaa",farmland:"Põllumaa",orchard:"Viljapuuaed",heath:"Nõmm",scrub:"Põõsastik",residential:"Hoonestatud ala",industrial:"Tööstusala",commercial:"Äriala",cemetery:"Haljasala",recreation_ground:"Haljasala"};
  try{
    const soil=L.tileLayer.wms("https://kaart.maaamet.ee/wms/alus-geo?",{layers:"mullaraster",format:"image/png",transparent:true,version:"1.1.1",attribution:"Mullastiku kaart, Maa- ja Ruumiamet"});
    const land=L.tileLayer.wms("https://kaart.maaamet.ee/wms/alus-geo?",{layers:"BK_METS,BK_LAGE,BK_SOO,BK_RABA,BK_POLD,BK_POOSASTIK,BK_ASUSTUS,BK_HALJASALA",format:"image/png",transparent:true,version:"1.1.1",attribution:"Maakate, Maa- ja Ruumiamet"});
    const ortho=L.tileLayer.wms("https://kaart.maaamet.ee/wms/alus-geo?",{layers:"of10000",format:"image/jpeg",transparent:false,version:"1.1.1",attribution:"Ortofoto, Maa- ja Ruumiamet"});
    L.control.layers({}, {"MaRu ortofoto":ortho,"MaRu mullakaart":soil,"MaRu maakate":land},{collapsed:true}).addTo(map);
  }catch(e){console.warn("MaRu map layers",e)}

  const avg=a=>{const v=(a||[]).map(Number).filter(Number.isFinite);return v.length?v.reduce((s,x)=>s+x,0)/v.length:null};
  async function elevation(lat,lon){try{const r=await fetch(`https://api.open-meteo.com/v1/elevation?latitude=${lat}&longitude=${lon}`),d=await r.json(),v=Number(d.elevation?.[0]);return Number.isFinite(v)?{label:`${Math.round(v)} m`,detail:"Copernicus DEM GLO-90 · 90 m"}:null}catch(e){return null}}
  async function weather(lat,lon){try{const u=new URL("https://api.open-meteo.com/v1/forecast");u.searchParams.set("latitude",lat);u.searchParams.set("longitude",lon);u.searchParams.set("hourly","soil_moisture_0_to_7cm,shortwave_radiation,cloud_cover");u.searchParams.set("past_days","7");u.searchParams.set("forecast_days","1");u.searchParams.set("timezone","auto");const d=await(await fetch(u)).json(),m=avg(d.hourly?.soil_moisture_0_to_7cm),rad=avg((d.hourly?.shortwave_radiation||[]).filter(x=>Number(x)>0)),cloud=avg(d.hourly?.cloud_cover);return{moistureLabel:m==null?null:m<.18?"Pigem kuiv":m<.30?"Keskmine":"Pigem niiske",moistureDetail:m==null?null:`${m.toFixed(2)} m³/m³ · viimase 7 päeva mudel`,lightLabel:rad==null?null:rad<120?"Vähe valgust":rad<260?"Keskmine":"Palju valgust",lightDetail:rad==null?null:`${Math.round(rad)} W/m² päevavalguse ajal${cloud!=null?` · pilvisus ${Math.round(cloud)}%`:""}`}}catch(e){return null}}
  async function landCover(lat,lon){try{const q=`[out:json][timeout:8];(way(around:120,${lat},${lon})[\"landuse\"];relation(around:120,${lat},${lon})[\"landuse\"];way(around:120,${lat},${lon})[\"natural\"];relation(around:120,${lat},${lon})[\"natural\"];);out tags center 30;`,r=await fetch("https://overpass-api.de/api/interpreter?data="+encodeURIComponent(q)),d=await r.json(),vals=[];for(const x of d.elements||[]){const v=x.tags?.natural||x.tags?.landuse;if(v)vals.push(v)}const priority=["wetland","wood","forest","meadow","grass","farmland","heath","scrub","orchard","residential","recreation_ground","cemetery","industrial","commercial"],v=priority.find(p=>vals.includes(p))||vals[0];return v?{label:LAND_LABELS[v]||v.replaceAll("_"," "),detail:"OpenStreetMap · ~120 m ümbrus"}:null}catch(e){return null}}
  function soilUrl(prop,layer,lat,lon){const d=.01,p=new URLSearchParams({map:`/map/${prop}.map`,SERVICE:"WMS",VERSION:"1.3.0",REQUEST:"GetFeatureInfo",BBOX:`${lat-d},${lon-d},${lat+d},${lon+d}`,CRS:"EPSG:4326",WIDTH:"101",HEIGHT:"101",LAYERS:layer,STYLES:"",FORMAT:"image/tiff",QUERY_LAYERS:layer,INFO_FORMAT:"text/html",I:"50",J:"50",FEATURE_COUNT:"1"});return `https://maps.isric.org/mapserv?${p}`}
  async function soilValue(prop,layer,lat,lon){try{const t=(await(await fetch(soilUrl(prop,layer,lat,lon))).text()).replace(/<[^>]*>/g," ").replace(/\s+/g," "),n=[...t.matchAll(/-?\d+(?:\.\d+)?/g)].map(x=>Number(x[0])).filter(Number.isFinite);return n.length?n[n.length-1]/10:null}catch(e){return null}}
  async function soilData(lat,lon){const [ph,clay,sand]=await Promise.all([soilValue("phh2o","phh2o_0-5cm_Q0.5",lat,lon),soilValue("clay","clay_0-5cm_Q0.5",lat,lon),soilValue("sand","sand_0-5cm_Q0.5",lat,lon)]);if(ph==null&&clay==null&&sand==null)return null;let label="Mulla lõimis";if(clay!=null&&sand!=null)label=clay>=40?"Savine":sand>=70?"Liivane":clay>=25?"Saviliiv / liivsavi":"Keskmise lõimisega";const p=[];if(ph!=null)p.push(`pH ${ph.toFixed(1)}`);if(sand!=null)p.push(`liiv ${Math.round(sand)}%`);if(clay!=null)p.push(`savi ${Math.round(clay)}%`);return{label,detail:p.join(" · ")||"SoilGrids 250 m mudel"}}
  async function environment(lat,lon){const [e,w,l,s]=await Promise.all([elevation(lat,lon),weather(lat,lon),landCover(lat,lon),soilData(lat,lon)]);return{elevation:e,weather:w,land:l,soil:s}}
  function loading(){["elevationValue","landValue","soilValue","moistureValue","lightValue"].forEach(id=>{if($(id))$(id).textContent="…"});["elevationDetail","landDetail","soilDetail","moistureDetail","lightDetail"].forEach(id=>{if($(id))$(id).textContent="Laen andmeid…"})}
  function render(e){if(!e)return;$("elevationValue").textContent=e.elevation?.label||"Pole saadaval";$("elevationDetail").textContent=e.elevation?.detail||"Kõrgusandmeid ei saadud";$("landValue").textContent=e.land?.label||"Pole saadaval";$("landDetail").textContent=e.land?.detail||"Maastikuandmeid ei saadud";$("soilValue").textContent=e.soil?.label||"Pole saadaval";$("soilDetail").textContent=e.soil?.detail||"SoilGridsi punktandmeid ei saadud";$("moistureValue").textContent=e.weather?.moistureLabel||"Pole saadaval";$("moistureDetail").textContent=e.weather?.moistureDetail||"Niiskusandmeid ei saadud";$("lightValue").textContent=e.weather?.lightLabel||"Pole saadaval";$("lightDetail").textContent=e.weather?.lightDetail||"Valgusandmeid ei saadud";
    const chips=[];if(e.elevation?.label)chips.push(e.elevation.label);if(e.land?.label)chips.push(e.land.label);if(e.weather?.moistureLabel)chips.push(e.weather.moistureLabel);if(e.weather?.lightLabel)chips.push(e.weather.lightLabel);const box=$("verdict");const target=box?.querySelector(".result-chips");if(target){target.querySelectorAll(".env-added").forEach(x=>x.remove());chips.forEach(c=>target.insertAdjacentHTML("beforeend",`<span class="result-chip env-added">${esc(c)}</span>`))}
    const ev=$("evidenceList");if(ev&&e.soil)ev.insertAdjacentHTML("beforeend",`<div class="evidence-row env-added"><span>◌</span><div><small>Muld</small><b>${esc(e.soil.label)}</b><p>${esc(e.soil.detail)}</p></div></div>`);
  }
  const base=runCheck;
  runCheck=async function(){loading();await base();if(chosenLocation){const e=await environment(chosenLocation.lat,chosenLocation.lon);render(e)}};
})();
